import os
import joblib
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
)

# ============================================================
# CONFIGURATION
# ============================================================

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(BASE_DIR, "ml_training_data.csv")
MODEL_DIR = os.path.join(BASE_DIR, "ml", "models")

os.makedirs(MODEL_DIR, exist_ok=True)

# ============================================================
# LOAD DATA
# ============================================================

print("=" * 60)
print("SMART ANTI-PROXY ATTENDANCE - ML TRAINING")
print("=" * 60)

print("\nLoading dataset...")

df = pd.read_csv(DATA_PATH)

print(f"Dataset shape: {df.shape}")

# ============================================================
# BASIC VALIDATION
# ============================================================

required_columns = [
    "attendance_id",
    "student_id",
    "session_id",
    "qr_version",
    "pin_correct",
    "typing_time",
    "scan_to_submit_time",
    "fingerprint_hash",
    "duplicate_hash",
    "duplicate_ip",
    "duplicate_browser",
    "duplicate_device",
    "duplicate_session",
    "risk_score",
    "rule_label",
    "teacher_label",
    "created_at",
    "latitude",
    "longitude",
    "gps_accuracy",
    "distance_from_campus",
    "inside_geofence",
]

missing_columns = [
    column for column in required_columns
    if column not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Dataset is missing columns: {missing_columns}"
    )

if df["teacher_label"].isna().any():
    raise ValueError("teacher_label contains missing values.")

print("Dataset structure: OK")

# ============================================================
# TARGET
# ============================================================

TARGET = "teacher_label"

X = df.drop(columns=[TARGET])
y = df[TARGET]

print("\nTarget distribution:")
print(y.value_counts())

# ============================================================
# REMOVE IDENTIFIERS / LEAKAGE
# ============================================================

# These fields should NOT be directly used by the first ML model.
#
# attendance_id  -> record identifier
# student_id     -> student identifier
# session_id     -> session identifier
# fingerprint_hash -> device identifier
#
# risk_score and rule_label are generated by the existing
# rule-based anti-proxy system. Including them would allow the
# ML model to simply learn/copy the existing rule engine.
#
# created_at is also removed initially because raw timestamps
# are not useful without deliberate time-feature engineering.

DROP_COLUMNS = [
    "attendance_id",
    "student_id",
    "session_id",
    "fingerprint_hash",
    "risk_score",
    "rule_label",
    "created_at",
]

X = X.drop(columns=DROP_COLUMNS)

print("\nFeatures used for ML:")
for column in X.columns:
    print(" -", column)

# ============================================================
# TRAIN / TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y,
)

print("\nTrain samples:", len(X_train))
print("Test samples:", len(X_test))

# ============================================================
# IDENTIFY FEATURE TYPES
# ============================================================

categorical_features = []

numeric_features = [
    "qr_version",
    "pin_correct",
    "typing_time",
    "scan_to_submit_time",
    "duplicate_hash",
    "duplicate_ip",
    "duplicate_browser",
    "duplicate_device",
    "duplicate_session",
    "latitude",
    "longitude",
    "gps_accuracy",
    "distance_from_campus",
    "inside_geofence",
]

# Verify that every remaining feature is accounted for.
remaining_features = set(X.columns)
expected_features = set(numeric_features + categorical_features)

unknown_features = remaining_features - expected_features

if unknown_features:
    raise ValueError(
        f"Unexpected features found: {unknown_features}"
    )

# ============================================================
# PREPROCESSING
# ============================================================

numeric_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        ),
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numeric",
            numeric_pipeline,
            numeric_features,
        ),
    ],
    remainder="drop",
)

# ============================================================
# MODELS
# ============================================================

models = {
    "logistic_regression": LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        random_state=42,
    ),

    "random_forest": RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        min_samples_split=4,
        min_samples_leaf=2,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    ),
}

# ============================================================
# TRAIN + EVALUATE
# ============================================================

results = []

for model_name, model in models.items():

    print("\n" + "=" * 60)
    print(f"TRAINING: {model_name}")
    print("=" * 60)

    pipeline = Pipeline(
        steps=[
            (
                "preprocessor",
                preprocessor
            ),
            (
                "model",
                model
            ),
        ]
    )

    pipeline.fit(X_train, y_train)

    predictions = pipeline.predict(X_test)

    probabilities = pipeline.predict_proba(X_test)[:, 1]

    accuracy = accuracy_score(
        y_test,
        predictions
    )

    precision = precision_score(
        y_test,
        predictions,
        zero_division=0,
    )

    recall = recall_score(
        y_test,
        predictions,
        zero_division=0,
    )

    f1 = f1_score(
        y_test,
        predictions,
        zero_division=0,
    )

    roc_auc = roc_auc_score(
        y_test,
        probabilities,
    )

    print("\nAccuracy :", round(accuracy, 4))
    print("Precision:", round(precision, 4))
    print("Recall   :", round(recall, 4))
    print("F1 Score :", round(f1, 4))
    print("ROC-AUC  :", round(roc_auc, 4))

    print("\nClassification Report:")
    print(
        classification_report(
            y_test,
            predictions,
            target_names=[
                "Legitimate",
                "Suspicious",
            ],
            zero_division=0,
        )
    )

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, predictions))

    results.append(
        {
            "model": model_name,
            "accuracy": accuracy,
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "roc_auc": roc_auc,
        }
    )

    # Save each trained pipeline.
    model_path = os.path.join(
        MODEL_DIR,
        f"{model_name}.joblib"
    )

    joblib.dump(
        pipeline,
        model_path
    )

    print(
        f"\nSaved model → {model_path}"
    )

# ============================================================
# COMPARE MODELS
# ============================================================

results_df = pd.DataFrame(results)

print("\n" + "=" * 60)
print("MODEL COMPARISON")
print("=" * 60)

print(
    results_df.sort_values(
        by="f1",
        ascending=False
    ).to_string(index=False)
)

# ============================================================
# SELECT BEST MODEL
# ============================================================

best_model_name = (
    results_df
    .sort_values(
        by="f1",
        ascending=False
    )
    .iloc[0]["model"]
)

best_model_path = os.path.join(
    MODEL_DIR,
    f"{best_model_name}.joblib"
)

# Copy/reference the best model under a stable filename.
best_model = joblib.load(best_model_path)

final_model_path = os.path.join(
    MODEL_DIR,
    "anti_proxy_model.joblib"
)

joblib.dump(
    best_model,
    final_model_path
)

print("\n" + "=" * 60)
print("BEST MODEL")
print("=" * 60)

print("Selected:", best_model_name)
print("Saved as:", final_model_path)

print("\nTraining completed successfully.")